# Generated by Django 5.2.3 on 2025-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_accused_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_magistrate', 'Awaiting Magistrate Approval'), ('under_review', 'Under Review'), ('fir_registered', 'FIR Registered'), ('gd_recorded', 'GD Recorded'), ('resolved', 'Resolved'), ('under_investigation', 'Under Investigation')], default='pending', max_length=20),
        ),
    ]
